DROP TABLE IF EXISTS balatro_jokers;

CREATE TABLE balatro_jokers (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL
);

INSERT INTO balatro_jokers (nombre, descripcion) VALUES
('Joker', '+4 Multiplicador'),
('Greedy Joker', 'Las cartas jugadas del palo Diamantes dan +3 Multiplicador al puntuar'),
('Lusty Joker', 'Las cartas jugadas del palo Corazones dan +3 Multiplicador al puntuar'),
('Wrathful Joker', 'Las cartas jugadas del palo Picas dan +3 Multiplicador al puntuar'),
('Gluttonous Joker', 'Las cartas jugadas del palo Tréboles dan +3 Multiplicador al puntuar'),
('Jolly Joker', '+8 Multiplicador si la mano jugada contiene una Pareja'),
('Zany Joker', '+12 Multiplicador si la mano jugada contiene un Trío'),
('Mad Joker', '+10 Multiplicador si la mano jugada contiene Doble Pareja'),
('Crazy Joker', '+12 Multiplicador si la mano jugada contiene una Escalera'),
('Droll Joker', '+10 Multiplicador si la mano jugada contiene un Color'),
('Sly Joker', '+50 Fichas si la mano jugada contiene una Pareja'),
('Wily Joker', '+100 Fichas si la mano jugada contiene un Trío'),
('Clever Joker', '+80 Fichas si la mano jugada contiene Doble Pareja'),
('Devious Joker', '+100 Fichas si la mano jugada contiene una Escalera'),
('Crafty Joker', '+80 Fichas si la mano jugada contiene un Color'),
('Half Joker', '+20 Multiplicador si la mano jugada tiene 3 o menos cartas'),
('Joker Stencil', 'X1 Multiplicador por cada espacio de Joker vacío'),
('Four Fingers', 'Todos los Colores y Escaleras se pueden hacer con 4 cartas'),
('Mime', 'Reactiva todas las habilidades de las cartas que se tienen en la mano'),
('Credit Card', 'Permite tener hasta -$20 de deuda'),
('Ceremonial Dagger', 'Al seleccionar la Ciega, destruye el Joker a la derecha y añade el doble de su valor de venta a su Multiplicador'),
('Banner', '+30 Fichas por cada descarte restante'),
('Mystic Summit', '+15 Multiplicador cuando quedan 0 descartes'),
('Marble Joker', 'Añade una carta de Piedra a tu mazo cuando se selecciona la Ciega'),
('Loyalty Card', 'X4 Multiplicador cada 6 manos jugadas'),
('8 Ball', '1 en 4 probabilidades de crear una carta de Tarot al puntuar un 8'),
('Misprint', 'Da un Multiplicador aleatorio entre +0 y +23'),
('Dusk', 'Reactiva todas las cartas jugadas en la última mano de la ronda'),
('Raised Fist', 'Añade el doble del valor de la carta más baja en tu mano al Multiplicador'),
('Chaos the Clown', 'Otorga 1 rediseño (reroll) gratis por tienda'),
('Fibonacci', 'Cada As, 2, 3, 5 u 8 jugado otorga +8 Multiplicador al puntuar'),
('Steel Joker', 'Gana X0.2 Multiplicador por cada carta de Acero en tu mazo completo'),
('Scary Face', 'Las cartas de figura (J, Q, K) jugadas dan +30 Fichas al puntuar'),
('Abstract Joker', '+3 Multiplicador por cada Joker que poseas'),
('Delayed Gratification', 'Gana $2 por cada descarte si no usas ninguno al final de la ronda'),
('Hack', 'Reactiva cada 2, 3, 4 o 5 jugado'),
('Pareidolia', 'Todas las cartas se consideran cartas de figura (J, Q, K)'),
('Gros Michel', '+15 Multiplicador. 1 en 6 probabilidades de ser destruido al final de la ronda'),
('Even Steven', 'Las cartas jugadas con valor par (2, 4, 6, 8, 10) dan +4 Multiplicador al puntuar'),
('Odd Todd', 'Las cartas jugadas con valor impar (A, 3, 5, 7, 9) dan +31 Fichas al puntuar'),
('Scholar', 'Los Ases jugados dan +20 Fichas y +4 Multiplicador al puntuar'),
('Business Card', 'Las cartas de figura jugadas tienen 1 en 2 probabilidades de dar $2 al puntuar'),
('Supernova', 'Añade al Multiplicador el número de veces que se ha jugado la mano de póker actual en esta partida'),
('Ride the Bus', 'Gana +1 Multiplicador por cada mano jugada consecutiva sin puntuar cartas de figura'),
('Space Joker', '1 en 4 probabilidades de mejorar el nivel de la mano de póker jugada'),
('Egg', 'Gana $3 de valor de venta al final de cada ronda'),
('Burglar', 'Al seleccionar la Ciega, pierdes todos los descartes y ganas +3 manos'),
('Blackboard', 'X3 Multiplicador si todas las cartas retenidas en la mano son Picas o Tréboles'),
('Runner', 'Gana +10 Fichas cada vez que juegas una Escalera'),
('Ice Cream', '+100 Fichas. Pierde 5 Fichas por cada mano jugada'),
('Splash', 'Todas las cartas jugadas puntúan, incluso si no forman parte de la mano ganadora'),
('Blue Joker', '+2 Fichas por cada carta restante en tu mazo'),
('Constellation', 'Gana X0.1 Multiplicador cada vez que usas una carta de Planeta'),
('Green Joker', '+1 Multiplicador por mano jugada, -1 Multiplicador por descarte'),
('Bloodstone', '1 en 2 probabilidades de que las cartas de Corazones jugadas den X1.5 Multiplicador'),
('Arrowhead', 'Las cartas de Picas jugadas dan +50 Fichas al puntuar'),
('Onyx Agate', 'Las cartas de Tréboles jugadas dan +7 Multiplicador al puntuar'),
('Glass Joker', 'Gana X0.5 Multiplicador por cada carta de Cristal destruida'),
('Showman', 'Los Jokers, cartas de Tarot, Planeta y Espectrales pueden aparecer varias veces en la tienda'),
('Flower Pot', 'X3 Multiplicador si la mano jugada contiene una carta de Picas, Corazones, Tréboles y Diamantes que puntúen'),
('Blueprint', 'Copia la habilidad del Joker a su derecha'),
('Brainstorm', 'Copia la habilidad del Joker que esté más a la izquierda'),
('Oops! All 6s', 'Duplica todas las probabilidades listadas (Ej: 1 en 4 se convierte en 2 en 4)'),
('The Idol', 'Cada carta jugada de un valor y palo aleatorios otorga X2 Multiplicador. Cambia cada ronda'),
('Vampire', 'Gana X0.1 Multiplicador por cada carta mejorada jugada; elimina la mejora de la carta'),
('Hologram', 'Gana X0.25 Multiplicador cada vez que añades una carta a tu mazo'),
('Baron', 'Cada Rey (K) en tu mano otorga X1.5 Multiplicador'),
('Obelisk', 'Gana X0.2 Multiplicador por cada mano jugada que NO sea tu mano de póker más jugada'),
('Photograph', 'La primera carta de figura jugada otorga X2 Multiplicador al puntuar'),
('Yorick', 'Multiplicador X5 después de descartar 23 veces (Joker Legendario)'),
('Perkeo', 'Crea una copia "Negativa" de una carta consumible aleatoria en tu posesión al final de la tienda (Joker Legendario)'),
('Triboulet', 'Reyes y Reinas otorgan X2 Multiplicador al puntuar (Joker Legendario)'),
('Chicot', 'Desactiva los efectos de las Ciegas Jefes (Joker Legendario)');
